/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestJNI */

#ifndef _Included_TestJNI
#define _Included_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestJNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestJNI
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestJNI_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestJNI
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestJNI_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestJNI
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestJNI_div
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TestJNI
 * Method:    concatStrings
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TestJNI_concatStrings
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     TestJNI
 * Method:    substring
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TestJNI_substring
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     TestJNI
 * Method:    stringLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_TestJNI_stringLength
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TestJNI
 * Method:    toUpperCase
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TestJNI_toUpperCase
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
